/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/boom_box/boombox_1k.gltf -t -r public 
*/
import React, { useRef } from "react";

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane095: THREE.Mesh;
    Plane095_1: THREE.Mesh;
  };
  materials: {
    boombox: THREE.MeshStandardMaterial;
    boombox_speakers: THREE.MeshStandardMaterial;
  };
};

export function Boombox(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/boom_box/boombox_1k.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane095.geometry} material={materials.boombox} />
      <mesh castShadow receiveShadow geometry={nodes.Plane095_1.geometry} material={materials.boombox_speakers} />
    </group>
  );
}

useGLTF.preload("/boom_box/boombox_1k.gltf");
