import { useContext } from "react";

import { GroupProps, useFrame } from "@react-three/fiber";

import { MeshContext } from "../context/MeshContext";
import BackgroundComputers from "./BackgroundComputers/BackgroundComputers";
import { Boombox } from "./Boombox";
import CommandLineScreen from "./CommandLineScreen/CommandLineScreen";
import { GamePad } from "./Gamepad";
import Leds from "./Leds/Leds";
import { RubberDuck } from "./RubberDuck";
import { SNES } from "./SNES";
import { Television } from "./Television/Television";
import VideoNoice from "./VideoNoice/VideoNoice";

/*
The following was auto-generated by: npx gltfjsx computers.glb --transform --instance
By using the --instance flag it detects similar geometry and instances it, thereby minimizing draw-calls

Author: Rafael Rodrigues (https://sketchfab.com/RafaelBR873D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-computers-7bb6e720499a467b8e0427451d180063
Title: Old Computers
*/

export const Computers: React.FC<GroupProps> = ({ ...props }) => {
  const { instances: Mesh, nodes: n, materials: m } = useContext(MeshContext);

  if (!Mesh) return <></>;

  return (
    <group {...props} dispose={null}>
      {/* Keyboards */}
      <Mesh.Keyboard position={[-3.2, 0.2, 0.18]} rotation={[-0.37, -0.2, -0.1]} scale={0.45} />

      {/* Left Stack */}
      <Mesh.Computer position={[-2.36, 0.32, -2.02]} rotation={[0, 0.53, -Math.PI / 2]} scale={1.52} />
      <Mesh.Object23 position={[-2.4, 1.56, -2.26]} rotation={[0, -0.005, -Math.PI / 2]} scale={1.52} />
      <Mesh.Object24 position={[-2.5, 2.19, -1.87]} rotation={[0, 0.4, Math.PI / 2]} scale={-1.52} />
      <mesh
        castShadow
        receiveShadow
        geometry={n.Object_24.geometry}
        material={m.Texture}
        position={[-2.42, 0.94, -2.25]}
        rotation={[0, 0.14, Math.PI / 2]}
        scale={-1.52}
      />

      {/* Center Stack */}
      <group position={[0, 0, 2.8]}>
        <Television position={[0.3, 2.52, -2.5]} scale={[1.1, 1.1, 1.1]} />
        <Mesh.Sphere position={[-0.445, 1.64, -1.75]} scale={0.01} color={[1, 0, 0]} />
        <Mesh.Computer position={[0.8, 0, -2.8]} rotation={[0, 0.17, 0]} scale={1.52} />
        <mesh
          castShadow
          receiveShadow
          geometry={n.Object_18.geometry}
          material={m.Texture}
          position={[-0.27, 0, -2.6]}
          rotation={[0, -0.06, 0]}
          scale={1.52}
        />
      </group>

      {/* Furthest Left */}
      <Mesh.Object3 position={[-3.79, 0, 1.66]} rotation={[Math.PI, -1.39, 0]} scale={-1.52} />
      <Mesh.Computer position={[-3.53, 1.53, 0.59]} rotation={[0, 0.91, 0]} scale={1.52} />
      <Mesh.Computer position={[-3.53, 0, 0.59]} rotation={[Math.PI, -1.09, Math.PI]} scale={1.52} />
      <Mesh.Computer position={[-3.69, 0, 2.59]} rotation={[0, -1.57, 0]} scale={1.52} />
      <Mesh.Object3 position={[-3.79, 1.53, 1.66]} rotation={[0, 1.22, -Math.PI]} scale={-1.52} />

      {/* Screen Right */}
      <CommandLineScreen
        text={`React, Machine Learning, Node, Pro`}
        position={[3.11, 2.15, -0.18]}
        rotation={[0, -0.79, 0]}
        scale={0.81}
      />
      <Mesh.Object23 position={[3.22, 0, -0.8]} rotation={[0, -1.32, 0]} scale={1.52} />
      <Mesh.Object23 position={[3.53, 1.83, 0.44]} rotation={[-Math.PI, 1.32, Math.PI / 2]} scale={1.52} />
      <Mesh.Computer position={[3.42, 0, 0]} rotation={[-Math.PI, 1.13, -Math.PI]} scale={1.52} />

      {/* Furthest to the right */}
      <Mesh.Object24 position={[3.87, 0.32, 2.35]} rotation={[0, -1.53, -1.57]} scale={-1.52} />
      <Mesh.Object23 position={[4.26, 0.94, 2.22]} rotation={[0, -1, Math.PI / 2]} scale={1.52} />
      <Mesh.Computer position={[4.09, 2.18, 2.41]} rotation={[0, -1.55, 1.57]} scale={1.52} />
      <Mesh.Object3 position={[4.31, 1.57, 2.34]} rotation={[0, -1.15, -Math.PI / 2]} scale={-1.52} />
      <Mesh.Object36 position={[3.95, 2.49, 1.61]} rotation={[0, -Math.PI / 3, 0]} />

      {/* Right Stack */}
      <Mesh.Object36 position={[2, 1.61, -1.7]} rotation={[0, -Math.PI / 3, 0]} />
      <Mesh.Object36 position={[1.8, 0, -1.94]} rotation={[0, -1.0, 0]} scale={[1.5, 1, 1.5]} />
      <VideoNoice frame="Object_215" panel="Object_216" position={[1.84, 0.38, -1.3]} />

      <VideoNoice frame="Object_209" panel="Object_210" position={[-1.5, 2.5, -1.5]} rotation={[0, 0.8, 0]} />

      {/* Screen Left Stack */}
      <CommandLineScreen
        text="A web application replica with features similar to IMDB."
        position={[-2.73, 0.63, -0.52]}
        rotation={[0, 1.09, 0]}
      />
      <Mesh.Object23 position={[-2.9, 0.3, -1.47]} rotation={[Math.PI, -1.35, Math.PI / 2]} scale={1.52} />

      {/* 3d models */}
      <GamePad scale={4.5} position={[-2, 0, 1]} rotation={[0, Math.PI / 3, 0]} />
      <RubberDuck position={[3.7, 2.84, 1.6]} rotation={[0, -1.8, 0]} scale={1.3} />
      <group position={[-2.7, 0, 2]} rotation={[0, Math.PI / 2, 0]}>
        <Boombox scale={3} />
        <Mesh.Sphere position={[0.43, 0.07, 0.32]} scale={0.01} color={[1, 0, 0]} />
      </group>
      <SNES position={[-1.2, 0, 0]} scale={0.04} rotation={[0, -0.13, 0]} />

      <BackgroundComputers />
      <Leds />
    </group>
  );
};
