/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/game_pad/gamepad_1k.gltf -t -r public 
*/
import React from "react";

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    gamepad: THREE.Mesh;
  };
  materials: {
    gamepad: THREE.MeshStandardMaterial;
  };
};

export function GamePad(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/game_pad/gamepad_1k.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.gamepad.geometry} material={materials.gamepad} />
    </group>
  );
}

useGLTF.preload("/game_pad/gamepad_1k.gltf");
