/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/rubber_duck/rubber_duck_toy_1k.gltf -t -r public 
*/
import React from "react";

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    rubber_duck_toy: THREE.Mesh;
  };
  materials: {
    rubber_duck_toy: THREE.MeshStandardMaterial;
  };
};

export function RubberDuck(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/rubber_duck/rubber_duck_toy_1k.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.rubber_duck_toy.geometry} material={materials.rubber_duck_toy} />
    </group>
  );
}

useGLTF.preload("/rubber_duck/rubber_duck_toy_1k.gltf");
